package trabalhop2;

import java.util.*;

public class bloco_notas extends javax.swing.JFrame {

    public bloco_notas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jMenu1.setText("Menu");

        jMenuItem1.setText("Ordenar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Limpar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem2.setText("Fechar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String conteudo = this.jTextArea1.getText();
        String valor[] = conteudo.split("\n");
        
        Colecao_metodos arraylist = new Colecao_metodos(new ArrayList<Integer>());
        this.jTextArea1.setText("Tempo de carregamento do ordenar:\narraylist: " + arraylist.tempo_ordenar(valor) + "\n");
        
        Colecao_metodos vector = new Colecao_metodos(new Vector<Integer>());
        this.jTextArea1.setText(this.jTextArea1.getText() + "vector: " + vector.tempo_ordenar(valor) + "\n");
        
        Colecao_metodos linkedlist = new Colecao_metodos(new LinkedList<Integer>());
        this.jTextArea1.setText(this.jTextArea1.getText() + "linkedlist: " + linkedlist.tempo_ordenar(valor) + "\n");

        Colecao_metodos stack = new Colecao_metodos(new Stack<Integer>());
        this.jTextArea1.setText(this.jTextArea1.getText() + "stack: " + stack.tempo_ordenar(valor) + "\n");
        
        Colecao_metodos priorityqueue = new Colecao_metodos(new PriorityQueue<Integer>());
        this.jTextArea1.setText(this.jTextArea1.getText() + "priorityqueue: " + priorityqueue.tempo_ordenar(valor) + "\n");
        
        Colecao_metodos arraydeque = new Colecao_metodos(new ArrayDeque<Integer>());
        this.jTextArea1.setText(this.jTextArea1.getText() + "arraydeque: " + arraydeque.tempo_ordenar(valor) + "\n");

        Colecao_metodos treeset = new Colecao_metodos(new TreeSet<Integer>());
        this.jTextArea1.setText(this.jTextArea1.getText() + "treeset: " + treeset.tempo_ordenar(valor) + "\n");
        
        Colecao_metodos hashset = new Colecao_metodos(new HashSet<Integer>());
        this.jTextArea1.setText(this.jTextArea1.getText() + "hashset: " + hashset.tempo_ordenar(valor) + "\n");
        
        Colecao_metodos linkedhashset = new Colecao_metodos(new LinkedHashSet<Integer>());
        this.jTextArea1.setText(this.jTextArea1.getText() + "linkedhashset: " + linkedhashset.tempo_ordenar(valor) + "\n");

        Map_metodos hashmap = new Map_metodos(new HashMap<Integer,Integer>());
        this.jTextArea1.setText(this.jTextArea1.getText() + "hashmap: " + hashmap.tempo_ordenar(valor) + "\n");
        
        Map_metodos linkedhashmap = new Map_metodos(new LinkedHashMap<Integer,Integer>());
        this.jTextArea1.setText(this.jTextArea1.getText() + "linkedhashmap: " + linkedhashmap.tempo_ordenar(valor) + "\n");
        
        Map_metodos treemap = new Map_metodos(new TreeMap<Integer,Integer>());
        this.jTextArea1.setText(this.jTextArea1.getText() + "treemap: " + treemap.tempo_ordenar(valor) + "\n");
        
        Map_metodos hashtable = new Map_metodos(new Hashtable<Integer,Integer>());
        this.jTextArea1.setText(this.jTextArea1.getText() + "hashtable: " + hashtable.tempo_ordenar(valor) + "\n");
        
        Map_metodos identityhashmap = new Map_metodos(new IdentityHashMap<Integer,Integer>());
        this.jTextArea1.setText(this.jTextArea1.getText() + "identityhashmap: " + identityhashmap.tempo_ordenar(valor) + "\n");
        
        Map_metodos weakhashmap = new Map_metodos(new WeakHashMap<Integer,Integer>());
        this.jTextArea1.setText(this.jTextArea1.getText() + "weakhashmap: " + weakhashmap.tempo_ordenar(valor) + "\n");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.jTextArea1.setText("");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bloco_notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bloco_notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bloco_notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bloco_notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bloco_notas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
